---
title: "Seasonality of COVID-19 Cases"
author: "Sarah Tillman"
date: "6/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyverse)
library(tidyr)
```
```{r data import}
# load in health equity data Jun - Nov 2020
raw_eq_info_nov <- read_csv("../Health_equity_data.csv", col_names = F)
# add in column names
colnames(raw_eq_info_nov) <- c("county", "date", "group", "cases")
# only select data for Durham County, NC
durham_nov_long <- raw_eq_info_nov[ which(raw_eq_info_nov$county=="Durham County, North Carolina"), ]
```

```{r remove meaningless variables}
# remove 2+ race column & county column and convert datatypes
durham_nov_long <- durham_nov_long %>%
  filter(group != "2+_races" & group != "native_hawaiian_pacific_islander") %>%
  select(-c(county))
durham_nov_long$cases <- as.numeric(durham_nov_long$cases)
```

```{r convert to short form}
# get list of all unique racial and ethnicity categories in data
race_eth_categories <- unique(durham_nov_long$group)
# initialize new table with each date only printed once
date <- unique(durham_nov_long$date)
durham_nov_short <- data.frame(date)
for(cat in race_eth_categories){
  single_group <- durham_nov_long %>%
    filter(group == cat) %>%
    select(-c(group))
  colnames(single_group)[2] <- cat
  durham_nov_short <-merge(durham_nov_short, single_group, by = "date", sort = TRUE)
}
```

```{r loading in Jun to Oct 2020 data }
unzip("../Race-and-Ethnicity-Data-1.1/Health_equity_data.csv.zip", list=T)
raw_oct_june_data <- read_csv(unzip("../Race-and-Ethnicity-Data-1.1/Health_equity_data.csv.zip", "Health_equity_data.csv"))
```
```{r}
colnames(raw_oct_june_data) <- c("county", "date", "group", "cases")
durham_jun_oct_long <- raw_oct_june_data[ which(raw_oct_june_data$county=="Durham County, North Carolina"), ]
```

```{r}
durham_jun_oct_long <- durham_jun_oct_long %>%
  filter(group != "2+_races" & group != "native_hawaiian_pacific_islander") %>%
  select(-c(county))
durham_jun_oct_long$cases <- as.numeric(durham_jun_oct_long$cases)
race_eth_categories <- unique(durham_jun_oct_long$group)
date <- unique(durham_jun_oct_long$date)
durham_jun_oct_short <- data.frame(date)
```

